version: "3"

volumes:
  db-data:
  cache-data:

services:
  db:
    image: postgres:alpine
    container_name: humblebrag-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5434"
    ports:
      - "5434:5434"
    volumes:
      - db-data:/var/lib/postgresql/data
    command: -p 5434

  cache:
    image: redis:alpine
    container_name: humblebrag-cache
    restart: always
    ports:
      - "6379:6379" # Changed from 6389:6389 to 6379:6379
    volumes:
      - cache-data:/data

networks:
  web_network:
    name: web_network
