version: '3.8'

services:
  clickhouse-db:
    image: yandex/clickhouse-server:latest
    container_name: humblebrag-clickhouse
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    platform: linux/amd64

  cache:
    image: redis:alpine
    container_name: humblebrag-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache-data:/data

networks:
  web_network:
    name: web_network

volumes:
  clickhouse-data:
  cache-data:
