version: "3.8"

services:
  db:
    image: postgres:alpine
    container_name: humblebrag-db
    environment:
      POSTGRES_DB: humblebrag
      POSTGRES_USER: codevaultllc
      POSTGRES_PASSWORD: 7c7ebd9a50c3ba4ae73e0c21b87c02f0267d23eb439bf55968472af46b3f8c5ca0f31cc6664d864e6df6d829c9c04c31693af43294e37c2e23c62c9dc469f815
    expose:
      - "5434"
    ports:
      - "5434:5434"
    volumes:
      - db-data:/var/lib/postgresql/data
    command: -p 5434
  cache:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - cache-data:/data

volumes:
  db-data:
  cache-data:
