version: "3"

volumes:
  db-data:
  cache-data:
  minio-data:

services:
  db:
    image: postgres:alpine
    container_name: humblebrag-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5434"
    ports:
      - "5434:5434"
    volumes:
      - db-data:/var/lib/postgresql/data
    command: -p 5434

  cache:
    image: redis:alpine
    container_name: humblebrag-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache-data:/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data
    volumes:
      - minio-data:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  web_network:
    name: web_network
