name: "Feature Request"
description: Create a new ticket for a new feature request
title: ""
labels: ["type: fr"]
body:
  - type: input
    id: fr-title
    attributes:
      label: "Feature Request Title"
      description: "A clear and concise title for the feature request"
      placeholder: "e.g. Add a new feature to the app"
      required: true
  - type: input
    id: fr-description
    attributes:
      label: "Feature Request Description"
      description: "A clear and concise description of what the feature request is."
      placeholder: "e.g. I would like to see a new feature in the app"
      required: true
  - type: markdown
      id: fr-template
      attributes:
        value: |
          **Describe the feature request**
          A clear and concise description of what the feature request is.

          **Additional context**
          Add any other context about the feature request here.
