apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minerva-ingress
  namespace: minerva-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: minerva.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minerva-service
            port:
              number: 3000
